### ISSUE TITLE
couldn't find any Index table of sciATAC-seq

### ISSUE THREAD

**Issue by eravza** [ParkerLab/islet_sci-ATAC-seq_2019#1]
I acquired sciATAC-seq data of yours though dbGap database. I was able to download pair-end fastq files but I couldn't find any Index table. In readme.md says "Both of these are available in dbGap repository under accession phs001188.v2.p1". 
But I couldn't find the index table. Where is the Index table exactly?

Thank you in advance.

**Comment by raivivek** [comment]
Hi @eravza! Thanks for bring this to our attention. This file was overlooked in the submission. While we update the dbGap submission, please download the indextable from [here](https://www.dropbox.com/sh/07icyratjwy0xwu/AAAGB32opo2V6QoWZBI6iO1va?dl=0). Let me know if you have any more questions!

**Comment by eravza** [comment]
Thank you for proving the file. I am trying to analyze pancreatic islet data of yours but I received the error below.
![error](https://user-images.githubusercontent.com/23385498/95797283-0a9d6d00-0ce7-11eb-86d3-713137374f56.png)

I checked "snatac-seq.split.log" file but it was empty. I don't know why I am getting the error.

Note: Before running snakemake, I tested by running `make dry_run` and everything was fine.

Can you help me with this issue, please?

Thank you in advance.

**Comment by raivivek** [comment]
Hi @eravza 

One way to debug this issue is to run the exact Python command that's being submitted to slurm and see if that works first. To find that command, run snakemake with ` -npr` flag which should also print the full command to be executed.

Let me know if that works successfully. If not, please send me the output message. If it does work, then there might be an issue with job submission.

**Comment by eravza** [comment]
I only run the script called 'sc_atac_10bpbarcode_split.py". I got "KeyError" error. Once I run it again the script without X argument, it worked without error but the majority of the output reads contain __AMBIG__  or __CTF__ flags. 
The reason I am deeply interested in this data is that in your paper, clustering method outputs 4 biologically distinct clusters.  I want to apply other clustering algorithms on the data to observe the difference between them.
I'll really appreciate if you could provide me with the location of the bam file. 
If you don't want to post it here, this is my email address, **emine.gur@gtc.ox.ac.uk**. I am a PhD student at the University of Oxford.
